version: "3.9"
services:
  reverse_proxy:
    image: nginx:1.19.9-alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  backend:
    build: ./todos-backend
    ports:
      - "8080:8080"
    volumes:
      - ./todos-backend/todos.sqlite:/app/todos.sqlite

  frontend:
    build: ./todos-frontend-react
    ports:
      - "3000:3000"
    volumes:
      - ./todos-frontend/src:/app/src
      - ./todos-frontend/public:/app/public
