version: "3.9"

services:
  todos:
    build: .
    ports:
      - "8080:8080"
    command: sh -c 'rm -fv ./todos && exec make watch-docker'
    volumes:
      - .:/app
    links:
      - webpack-dev-server

  webpack-dev-server:
    build: ./website
    ports:
      - "9000:9000"
    volumes:
      - ./website/src:/app/src
      - ./website/dist:/app/dist
