version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    command: sh -c 'rm -fv ./todos && exec make watch'
    environment:
      SERVER_FLAGS: "-address 0.0.0.0 -delay 1000"
    volumes:
      - .:/app

  webpack-dev-server:
    build: ./website
    ports:
      - "9000:9000"
    volumes:
      - ./website/src:/app/src
      - ./website/dist:/app/dist
